---
global:
  scrape_interval:     5s
  evaluation_interval: 1m
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'nomad_metrics'
    scrape_interval: 5s
    metrics_path: /v1/metrics
    scheme: https
    tls_config:
      ca_file: '/local/nomad-ca.pem'
      cert_file: '/local/nomad-cli-cert.pem'
      key_file: '/local/nomad-cli-key.pem'
      insecure_skip_verify: true 
    params:
      format: ['prometheus']
    consul_sd_configs:
    - server: '<LOAD_BALANCER_IP>:8501'
      token: '<CONSUL_METRICS_TOKEN>'
      datacenter: 'dc1'
      scheme: 'https'
      tls_config:
        ca_file: '/local/consul-ca.pem'
        cert_file: '/local/consul-cli-cert.pem'
        key_file: '/local/consul-cli-key.pem'
        insecure_skip_verify: false
      services: ['nomad-client', 'nomad']
    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep